In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Cố định "nhân phẩm" để kết quả luôn ổn định
tf.random.set_seed(42)
np.random.seed(42)

# 1. ĐẦU VÀO (X, Y) - Khớp với file Excel
X = np.array([[2.0], [3.0], [6.0], [8.0]])  # Giờ học
Y = np.array([[0.0], [0.0], [1.0], [1.0]])  # 0: Rớt, 1: Đậu

# 2. XÂY DỰNG MẠNG 3 LỚP (Khớp với mã giả L=3)
model = Sequential()
model.add(Dense(4, input_dim=1, activation='relu', name="Lop_An_1")) # Trạm 1
model.add(Dense(4, activation='relu', name="Lop_An_2"))              # Trạm 2
model.add(Dense(1, activation='sigmoid', name="Lop_Dau_Ra"))         # Trạm 3 (Output)

# 3. HUẤN LUYỆN (Tối ưu hóa W, b)
model.compile(loss='binary_crossentropy', optimizer='adam')
model.fit(X, Y, epochs=2000, verbose=0) # Cho chạy 2000 vòng

# ---------------------------------------------------------
# 4. IN KẾT QUẢ: MA TRẬN W VÀ VECTOR b ĐÃ HỌC ĐƯỢC
# ---------------------------------------------------------
print("🧠 BỘ THAM SỐ TỐI ƯU SAU KHI HUẤN LUYỆN")
print("(Khớp tuyệt đối với mã giả W[l] và b[l]):\n")

# Vòng lặp in tham số từng lớp (Khớp với vòng lặp FOR l=1 TO L)
for i, layer in enumerate(model.layers):
    W, b = layer.get_weights()
    print(f"--- LỚP {i+1} ({layer.name}) ---")
    print(f"Ma trận Trọng số W[{i+1}]:\n{W}")
    print(f"Vector Độ lệch b[{i+1}]:\n{b}\n")

# 5. DỰ ĐOÁN THỬ ĐỂ CHỨNG MINH W, b HOẠT ĐỘNG TỐT
print("📊 KIỂM TRA DỰ ĐOÁN:")
predictions = model.predict(X, verbose=0)
for i in range(len(X)):
    ket_qua = "ĐẬU" if predictions[i][0] > 0.5 else "RỚT"
    print(f"- Học {X[i][0]} giờ -> Output = {predictions[i][0]:.4f} ({ket_qua}) | Thực tế: {Y[i][0]}")

🧠 BỘ THAM SỐ TỐI ƯU SAU KHI HUẤN LUYỆN
(Khớp tuyệt đối với mã giả W[l] và b[l]):

--- LỚP 1 (Lop_An_1) ---
Ma trận Trọng số W[1]:
[[-0.39981997  0.52345216  0.9376045  -0.5938384 ]]
Vector Độ lệch b[1]:
[ 0.        -1.5702801 -0.4242185  0.       ]

--- LỚP 2 (Lop_An_2) ---
Ma trận Trọng số W[2]:
[[ 0.3591798  -0.09250647  0.09505457 -0.63104665]
 [-0.21054694 -0.05882197  0.04039216  1.6187717 ]
 [ 0.27450022  0.470851   -0.664393    0.5386827 ]
 [-0.7935051   0.07480931  0.22591668 -0.02074385]]
Vector Độ lệch b[2]:
[ 0.8925253   0.3164537   0.         -0.93315786]

--- LỚP 3 (Lop_Dau_Ra) ---
Ma trận Trọng số W[3]:
[[-1.0073617 ]
 [-0.11158559]
 [-0.19811988]
 [ 1.4277626 ]]
Vector Độ lệch b[3]:
[-0.9509227]

📊 KIỂM TRA DỰ ĐOÁN:
- Học 2.0 giờ -> Output = 0.0861 (RỚT) | Thực tế: 0.0
- Học 3.0 giờ -> Output = 0.1028 (RỚT) | Thực tế: 0.0
- Học 6.0 giờ -> Output = 0.9545 (ĐẬU) | Thực tế: 1.0
- Học 8.0 giờ -> Output = 0.9985 (ĐẬU) | Thực tế: 1.0
